# -*- coding: utf-8 -*-
"""calculator

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1a5Bxfur4EFeMcWSpsXhh_V0efrxmbtAC
"""

import streamlit as st

# Define the calculator functions
def add(num1, num2):
    return num1 + num2

def subtract(num1, num2):
    return num1 - num2

def multiply(num1, num2):
    return num1 * num2

def divide(num1, num2):
    if num2 == 0:
        return "Division by zero is not allowed"
    else:
        return num1 / num2

# Dictionary to map symbols to functions
operations = {'+': add, '-': subtract, '*': multiply, '/': divide}

# Streamlit app code
def calculator():
    st.title("Basic Calculator App")

    # Retain the result for subsequent calculations
    result = st.session_state.get("result", None)

    # Use previous result if available
    num1 = st.number_input("Enter the first number", value=result if result else 0.0)
    operation_symbol = st.selectbox("Pick an operation", list(operations.keys()))
    num2 = st.number_input("Enter the second number", value=0.0)

    # Perform calculation when the "Calculate" button is pressed
    if st.button("Calculate"):
        calculation_function = operations[operation_symbol]
        answer = calculation_function(num1, num2)
        st.write(f"**{num1} {operation_symbol} {num2} = {answer}**")

        # Save result for the next calculation
        st.session_state["result"] = answer

    # Clear session state if user wants to start over
    if st.button("Clear"):
        st.session_state["result"] = None
        st.experimental_rerun()

# Call the calculator function in Streamlit
if __name__ == '__main__':
    calculator()